// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitaryDraftSystem.Infrastructure.Persistence;

#nullable disable

namespace MilitaryDraftSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728204104_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Summons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CitizenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId");

                    b.ToTable("Summons");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Summons", b =>
                {
                    b.HasOne("MilitaryDraftSystem.Domain.Entities.Citizen", null)
                        .WithMany("Summonses")
                        .HasForeignKey("CitizenId");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Citizen", b =>
                {
                    b.Navigation("Summonses");
                });
#pragma warning restore 612, 618
        }
    }
}
