// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilitaryDraftSystem.Infrastructure.Persistence;

#nullable disable

namespace MilitaryDraftSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912213226_AddCitizenAndOfficerLifecycle")]
    partial class AddCitizenAndOfficerLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.AutomaticRecruitmentAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ExecutionInterval")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastExecutionAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AutomaticRecruitmentAgents");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.CemeteryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OriginalRecordDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CemeteryRecords");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCriminalRecord")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MedicalCategory")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NaturalLifespanYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.DeathStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeathStatistics");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.God", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CriminalRecordChance")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("GenerationInterval")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastGenerationAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCitizensPerGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinCitizensPerGeneration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentChance")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Gods");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.RecruitmentOfficer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DraftedCitizensCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GuiltIncidentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoralePercent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecruitmentOfficers");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Summons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AutomaticRecruitmentAgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecruitmentOfficerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Summonses");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.WorkerLifecycleStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WorkerLifecycleStatistics");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.Citizen", b =>
                {
                    b.OwnsOne("MilitaryDraftSystem.Domain.ValueObjects.Death", "Death", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Reason")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizens");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.Navigation("Death");
                });

            modelBuilder.Entity("MilitaryDraftSystem.Domain.Entities.RecruitmentOfficer", b =>
                {
                    b.OwnsOne("MilitaryDraftSystem.Domain.ValueObjects.Death", "Death", b1 =>
                        {
                            b1.Property<Guid>("RecruitmentOfficerId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Reason")
                                .HasColumnType("INTEGER");

                            b1.HasKey("RecruitmentOfficerId");

                            b1.ToTable("RecruitmentOfficers");

                            b1.WithOwner()
                                .HasForeignKey("RecruitmentOfficerId");
                        });

                    b.Navigation("Death");
                });
#pragma warning restore 612, 618
        }
    }
}
